"""Add assigned_number_1 and assigned_number_2 to Customer

Revision ID: 82f7201d281e
Revises: 
Create Date: 2026-01-10 16:15:12.199900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f7201d281e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_status', schema=None) as batch_op:
        batch_op.create_index('idx_calls_user_status', ['customer_id', 'status'], unique=False)

    with op.batch_alter_table('call_log', schema=None) as batch_op:
        batch_op.create_index('idx_timestamp', ['call_timestamp'], unique=False)

    with op.batch_alter_table('contact_calling_list', schema=None) as batch_op:
        batch_op.create_index('idx_concal_customer_calling_list', ['customer_id', 'calling_list_id'], unique=False)

    with op.batch_alter_table('contact_list', schema=None) as batch_op:
        batch_op.create_index('idx_contacts_customer_id', ['customer_id'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_number_1', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('assigned_number_2', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['assigned_number_2'])
        batch_op.create_unique_constraint(None, ['assigned_number_1'])

    with op.batch_alter_table('twilio_calls', schema=None) as batch_op:
        batch_op.create_index('idx_calls_started_direction', ['started_at', 'direction'], unique=False)
        batch_op.create_index('idx_calls_user_status', ['customer_id', 'to_number'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_customer', ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('idx_user_customer')

    with op.batch_alter_table('twilio_calls', schema=None) as batch_op:
        batch_op.drop_index('idx_calls_user_status')
        batch_op.drop_index('idx_calls_started_direction')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('assigned_number_2')
        batch_op.drop_column('assigned_number_1')

    with op.batch_alter_table('contact_list', schema=None) as batch_op:
        batch_op.drop_index('idx_contacts_customer_id')

    with op.batch_alter_table('contact_calling_list', schema=None) as batch_op:
        batch_op.drop_index('idx_concal_customer_calling_list')

    with op.batch_alter_table('call_log', schema=None) as batch_op:
        batch_op.drop_index('idx_timestamp')

    with op.batch_alter_table('agent_status', schema=None) as batch_op:
        batch_op.drop_index('idx_calls_user_status')

    # ### end Alembic commands ###
