"""add_scheduled_call_column_to_call_log

Revision ID: 8b3aa537009a
Revises: 981c5ff4f77a
Create Date: 2026-04-29 13:10:53.621369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3aa537009a'
down_revision = '981c5ff4f77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_call', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_log', schema=None) as batch_op:
        batch_op.drop_column('scheduled_call')

    # ### end Alembic commands ###
