"""change recording_duration to float

Revision ID: 952812e20f34
Revises: 981c5ff4f77a
Create Date: 2026-03-07 16:09:27.142747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '952812e20f34'
down_revision = '981c5ff4f77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twilio_calls', schema=None) as batch_op:
        batch_op.alter_column('recording_duration',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.execute("UPDATE twilio_calls SET recording_duration = ROUND(recording_duration / 60, 2);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.execute("UPDATE twilio_calls SET recording_duration = ROUND(recording_duration * 60);")
     with op.batch_alter_table('twilio_calls', schema=None) as batch_op:
        batch_op.alter_column('recording_duration',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
   

    # ### end Alembic commands ###
