"""increase note column size

Revision ID: 981c5ff4f77a
Revises: 82f7201d281e
Create Date: 2026-01-30 22:59:00.134764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '981c5ff4f77a'
down_revision = '82f7201d281e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_calling_list', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_calling_list', schema=None) as batch_op:
        batch_op.alter_column('note',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
